POST http://localhost:3003/api/blogs
Content-Type: application/json

{    
        "title":"kuinka olla testi",
        "author":"testin luoja",
        "url": "test.testi.testin.testi",
        "likes": 45       
}